src/main/java/com/pokedex/SelectOneListBoxBean.java
package com.pokedex;

import java.util.List;
import javax.annotation.PostConstruct;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class SelectOneListBoxBean {

    private Pokemon pokemon;
    private List<Pokemon> pokemons;

    @ManagedProperty("#{pokemonService}")
    private PokemonService service;

    @PostConstruct
    public void init() {
        pokemons = service.getPokemons();

    }

    public Pokemon getPokemon() {
        if (pokemon != null) {
            Deiak.getInstance().id = pokemon.getId() + 1;
        }

        return pokemon;
    }

    public void setPokemon(Pokemon pokemon) {
        this.pokemon = pokemon;
    }

    public List<Pokemon> getPokemons() {
        return pokemons;
    }

    public void setService(PokemonService service) {
        this.service = service;
    }

    /* INFO 1 */
    public String getType1() {
        return Deiak.getInstance().getPokeType1();
    }
    
    public String getWeight() {
        return Integer.toString(Deiak.getInstance().getPokeWeight());
    }

    public String getHeight() {
        return Integer.toString(Deiak.getInstance().getPokeHeight());
    }

    public String getGen() {
        return Deiak.getInstance().getPokeGen();
    }

    /* INFO 2 */
    public String getGender() {
        float generoak = Deiak.getInstance().getPokeGender();
        if (generoak == -1) {
            return "unknown";
        }
        float em = (generoak / 8) * 100;
        return "♀" + em + "%     ♂" + (100 - em) + "%";
    }

    public String getColour() {
        return Deiak.getInstance().getPokeColour();
    }

    public String getShape() {
        return Deiak.getInstance().getPokeShape();
    }

    public String getHabitat() {
        return Deiak.getInstance().getPokeHabitat();
    }

    /* INFO 3*/
    public String getCaptureRate() {
        return Integer.toString(Deiak.getInstance().getPokeCaptureRate());
    }

    public String getHappiness() {
        return Integer.toString(Deiak.getInstance().getPokeHappiness());
    }

    public String getBaseExp() {
        return Integer.toString(Deiak.getInstance().getPokeBaseExp());
    }

    /* INFO 4 */
    public String getEgg() {
        return Deiak.getInstance().getPokeEgg();
    }

    public String getBaby() {
        int baby = Deiak.getInstance().getPokeBaby();
        if (baby == 0) {
            return "No";
        }
        return "Yes";
    }

    public String getHatch() {
        return Integer.toString(Deiak.getInstance().getPokeHatch());
    }

    public String getGrowRate() {
        return Deiak.getInstance().getPokeGrowthRate();
    }

    /* EVOLUTION */
    public String getEvolutions() {
        return Deiak.getInstance().getPokeEvolution();
    }

    /* STATS */
    public String getHP() {
        return Integer.toString(Deiak.getInstance().getPokeHP());
    }
    public String getAttack() {
        return Integer.toString(Deiak.getInstance().getPokeAttack());
    }
    public String getDefense() {
        return Integer.toString(Deiak.getInstance().getPokeDefense());
    }
    public String getSpeed() {
        return Integer.toString(Deiak.getInstance().getPokeSpeed());
    }
    public String getSpAtk() {
        return Integer.toString(Deiak.getInstance().getPokeSpAtk());
    }
    public String getSpDef() {
        return Integer.toString(Deiak.getInstance().getPokeSpDef());
    }
}

src/main/webapp/evolution.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Evolution">
        <h:outputText value="Evolution: " />
        <h:outputText value="#{selectOneListBoxBean.evolutions}" />

    </p:tab>

</ui:composition>

src/main/webapp/index.jsp
<%
    String redirectURL = "index.xhtml";
    response.sendRedirect(redirectURL);
%>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>HOME</title>
            </f:facet>

            <h:outputStylesheet name="css/body.css" />

        </h:head>

        <h:body class="body1" onkeyup="if (event.keyCode === 13) {
                    document.getElementById('img6').src = 'resources/irudiak/besteak/start.png';
                    location.href = './pokemonZerrenda.xhtml';
                    return false;
                }"
                onkeydown="if (event.keyCode === 13) {
                            document.getElementById('img6').src = 'resources/irudiak/besteak/start2.png';
                            return false;
                        }">
            <h:form>
                <div>
                    <img src="resources/irudiak/besteak/pokemon_logo.png" id="img1" name="img1" style="height: 200px;width: 700px;position:absolute;top:5%;left:5%;"/>
                    <img src="resources/irudiak/besteak/ho-oh.png" id="img2" name="img2" style="height: 250px;width: 250px;position:absolute;right:10%;top:10%;"/>
                    <img src="resources/irudiak/besteak/pidgeot.png" id="img3" name="img3" style="height: 130px;width: 130px;position:absolute;bottom: 30%;left:22%;"/>
                    <img src="resources/irudiak/besteak/munchlax.png" id="img4" name="img4" style="height: 110px;width: 110px;position:absolute;bottom: 12%;left:14%;"/>
                    <img src="resources/irudiak/besteak/totodile.png" id="img5" name="img5" style="height: 90px;width: 90px;position:absolute;bottom: 7%;left:25%;"/>
                    <img src="resources/irudiak/besteak/start.png" id="img6" name="img6" style="height: 110px;width: 250px;position:absolute;right:40%;top:40%;" 
                         onclick="location.href = './pokemonZerrenda.xhtml'" onmouseover="this.src = 'resources/irudiak/besteak/start2.png';" 
                         onmouseout="this.src = 'resources/irudiak/besteak/start.png';"/>
                </div>
            </h:form>
        </h:body>
    </f:view>
</html>

src/main/webapp/info1.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Info1">
        <h:outputText style="font-weight: bold;" value="Main Type: " />
        <h:outputText value="#{selectOneListBoxBean.type1}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Generation: " />
        <h:outputText value="#{selectOneListBoxBean.gen}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Weight: " />
        <h:outputText value="#{selectOneListBoxBean.weight}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Height: " />
        <h:outputText value="#{selectOneListBoxBean.height}" />

    </p:tab>

</ui:composition>

src/main/webapp/info2.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Info2">
        <h:outputText style="font-weight: bold;" value="Gender: " />
        <h:outputText value="#{selectOneListBoxBean.gender}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Colour: " />
        <h:outputText value="#{selectOneListBoxBean.colour}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Shape: " />
        <h:outputText value="#{selectOneListBoxBean.shape}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Habitat: " />
        <h:outputText value="#{selectOneListBoxBean.habitat}" />

    </p:tab>

</ui:composition>

src/main/webapp/info3.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Info3">
        <h:outputText style="font-weight: bold;" value="Capture Rate: " />
        <h:outputText value="#{selectOneListBoxBean.captureRate}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Happiness: " />
        <h:outputText value="#{selectOneListBoxBean.happiness}" />

        <br />

        <h:outputText style="font-weight: bold;" value="BaseExp: " />
        <h:outputText value="#{selectOneListBoxBean.baseExp}" />

    </p:tab>

</ui:composition>

src/main/webapp/info4.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Info4">
        <h:outputText style="font-weight: bold;" value="Egg: " />
        <h:outputText value="#{selectOneListBoxBean.egg}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Baby: " />
        <h:outputText value="#{selectOneListBoxBean.baby}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Hatch: " />
        <h:outputText value="#{selectOneListBoxBean.hatch}" />

        <br />

        <h:outputText style="font-weight: bold;" value="Growth rate: " />
        <h:outputText value="#{selectOneListBoxBean.growRate}" />

    </p:tab>

</ui:composition>

src/main/webapp/logIn.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>LogIn</title>
            </f:facet>
            <h:outputStylesheet name="css/body.css" />
        </h:head>
        <h:body>
            <img src="resources/irudiak/besteak/pidgeot.png" id="img3" name="img3" style="height: 130px;width: 130px;position:absolute;bottom: 30%;left:22%;"/>
            <img src="resources/irudiak/besteak/munchlax.png" id="img4" name="img4" style="height: 110px;width: 110px;position:absolute;bottom: 12%;left:14%;"/>
            <img src="resources/irudiak/besteak/totodile.png" id="img5" name="img5" style="height: 90px;width: 90px;position:absolute;bottom: 7%;left:25%;"/>
            <div style="position: absolute;top: 10%;left: 30%;border: 3px solid black; padding: 8px; border-radius: 8px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.25);">
                <h:form>
                    <p:messages showDetail="true"/>
                    <h:outputLabel for="date" value="Erabiltzailea:" />
                    <br />
                    <p:inputText id="date" label="username" required="true" placeholder="Erabiltzailea" value="#{erabiltzailea.izena}" >
                        <f:validateRegex pattern="[a-zA-Z]+"/>
                    </p:inputText>
                    <br />
                    <h:outputLabel for="password" value="Pasahitza:" />
                    <br />
                    <p:password id="password" required="true" label="password" placeholder="pasahitza" value="#{erabiltzailea.pasahitza}" >
                    </p:password>
                    <br />
                    <br />
                    <!--<p:captcha label="Captcha" />-->
                    <br />
                    <p:commandButton value="Baieztatua" action="#{erabiltzailea.logeatu}" ajax="false" icon="ui-icon-check"/>
                </h:form>
            </div>
            <ui:include src="stack.xhtml"/>
        </h:body>
    </f:view>
</html>

src/main/webapp/pokemonZerrenda.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:mp="http://primefaces.org/ui/material"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>           
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Zerrenda</title>
            </f:facet>

            <h:outputStylesheet name="css/body.css" />
            <h:outputStylesheet name="css/stats.css" />

        </h:head>

        <h:body class="body1">            
            <h:form>
                <div class="ui-g">
                    <div class="ui-g-12 ui-md-2">
                        <h3><p:outputLabel value="Pokemon Zerrenda" /></h3>
                        <p:selectOneListbox style="width: 200px;" value="#{selectOneListBoxBean.pokemon}" converter="pokemonConverter" filter="true" filterMatchMode="contains" var="p"
                                            scrollHeight="400">                            
                            <f:selectItems value="#{selectOneListBoxBean.pokemons}" var="pokemon"
                                           itemValue="#{pokemon}" itemLabel="#{pokemon.name}" />    
                            <f:ajax event="change" execute="@this" render="pokeImage" />                            
                            <p:column>
                                <p:graphicImage value="resources/irudiak/pokemon/#{p.id + 1}.png" width="40"/>
                            </p:column>
                            <p:column>
                                ##{p.id + 1} - #{p.name}
                            </p:column>
                        </p:selectOneListbox>
                    </div>
                    <div class="ui-g-12 ui-md-10 ui-g-nopad" id="pokeInfo">
                        <h:panelGroup id="pokeImage">
                            <h:panelGroup rendered="#{not(empty selectOneListBoxBean.pokemon.name)}">                                
                                <div style="text-align: center;">
                                    <h1><p:outputLabel  id="text" value="#{selectOneListBoxBean.pokemon.name}" style="size: portrait;" /></h1>
                                </div>
                                <br />

                                <div style="text-align: center;">
                                    <p:graphicImage value="resources/irudiak/pokemon/#{selectOneListBoxBean.pokemon.id + 1}.png" width="300" height="300"  cache="false" />
                                    <p:graphicImage value="resources/irudiak/gif/#{selectOneListBoxBean.pokemon.id + 1}.gif" cache="false"/>
                                </div>

                                <br />
                                <br />
                                <br />
                                <br />

                                <div style="text-align: center;">
                                    <p:tabView style="display: inline-block;">
                                        <ui:include src="info1.xhtml"/>
                                        <ui:include src="info2.xhtml"/>
                                        <ui:include src="info3.xhtml"/>
                                        <ui:include src="info4.xhtml"/>
                                        <ui:include src="evolution.xhtml"/>
                                        <ui:include src="stats.xhtml"/>
                                    </p:tabView>
                                </div>

                            </h:panelGroup>
                        </h:panelGroup>
                    </div>
                </div>    
                <h:panelGroup rendered="#{erabiltzailea.getSaioa() ne 'Anonimoa'}">
                    <div style="position: absolute; top: 10%; right: 7.5%;border: 3px solid black; padding: 8px; border-radius: 8px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.25);">
                        <br />
                        <p:outputLabel value="#{erabiltzailea.getSaioa()}" style="background-color: #dddddd; border: 3px solid black; padding: 8px; border-radius: 8px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.25);" />
                        <br />
                        <br />
                        <p:commandButton value="LogOut" actionListener="#{erabiltzailea.saioaItxi()}" icon="ui-icon-person" />
                    </div>
                </h:panelGroup>
            </h:form>
        </h:body>
    </f:view>
</html>

src/main/webapp/signUp.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>SignUp</title>
            </f:facet>
            <h:outputStylesheet name="css/body.css" />
        </h:head>
        <h:body>
            <img src="resources/irudiak/besteak/pidgeot.png" id="img3" name="img3" style="height: 130px;width: 130px;position:absolute;bottom: 30%;left:22%;"/>
            <img src="resources/irudiak/besteak/munchlax.png" id="img4" name="img4" style="height: 110px;width: 110px;position:absolute;bottom: 12%;left:14%;"/>
            <img src="resources/irudiak/besteak/totodile.png" id="img5" name="img5" style="height: 90px;width: 90px;position:absolute;bottom: 7%;left:25%;"/>
            <div style="position: absolute;top: 10%;left: 30%;border: 3px solid black; padding: 8px; border-radius: 8px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.25);">
                <h:form>
                    <p:messages showDetail="true"/>
                    <h:outputLabel for="date" value="Erabiltzailea:" />
                    <br />
                    <p:inputText id="date" label="username" required="true" placeholder="Mielotxim" value="#{erabiltzailea.izena}">
                        <f:validateRegex pattern="[a-zA-Z]+"/>
                    </p:inputText>
                    <br />
                    <h:outputLabel for="password" value="Pasahitza:" />
                    <br />
                    <p:password id="password" required="true" label="password" placeholder="xxxxxxxx" value="#{erabiltzailea.pasahitza}"/>
                    <br />
                    <br />
                    <!--<p:captcha label="Captcha" />-->
                    <br />
                    <p:commandButton value="Sign Up" action="#{erabiltzailea.erregistratu}" ajax="false" icon="ui-icon-check"/>
                </h:form>
            </div>
            <ui:include src="stack.xhtml"/>
        </h:body>
    </f:view>
</html>

src/main/webapp/stack.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <h:form>
        <p:stack icon="resources/irudiak/besteak/nothing.png" expanded="false">
            <p:menuitem value="Zerrenda" icon="resources/irudiak/besteak/PokeBall.png" url="./pokemonZerrenda.xhtml" />
            <p:menuitem value="LogIn" icon="resources/irudiak/besteak/SuperBall.png" url="./logIn.xhtml" />
            <p:menuitem value="SignUp" icon="resources/irudiak/besteak/UltraBall.png" url="./signUp.xhtml" />
        </p:stack>
    </h:form>
</ui:composition>

src/main/webapp/stats.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui">

    <p:tab title="Stats">
        <div class="detail-stats" style="margin: auto">
            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textHP" value="HP" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueHP" value="#{selectOneListBoxBean.HP}" />
                    </div>
                </span>
            </div>

            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textAttack" value="Attack" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueAttack" value="#{selectOneListBoxBean.attack}" />
                    </div>
                </span>
            </div>

            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textDefense" value="Defense" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueDefense" value="#{selectOneListBoxBean.defense}" />
                    </div>
                </span>
            </div>

            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textSpeed" value="Speed" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueSpeed" value="#{selectOneListBoxBean.speed}" />
                    </div>
                </span>
            </div>

            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textSpAtk" value="Sp Atk" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueSpAtk" value="#{selectOneListBoxBean.spAtk}" />
                    </div>
                </span>
            </div>

            <div class="detail-stats-row">
                <span>
                    <h:outputText id="textSpDef" value="Sp Def" />
                </span>
                <span class="stat-bar">
                    <div class="stat-bar-fg">
                        <h:outputText id="valueSpDef" value="#{selectOneListBoxBean.spDef}" />
                    </div>
                </span>
            </div>
        </div>
    </p:tab>
</ui:composition>